name: shopapp
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  dropdown_search: ^5.0.6
  cupertino_icons: ^1.0.8
  awesome_dialog: ^3.2.1
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter_native_splash:
  
  color: "#ffffff"
  image: assets/images/pic1.png
   

flutter:
  uses-material-design: true
  assets:
    - assets/images/


   
 